@HostAddress = http://localhost:5296

### Invoice ------------------------------
GET {{HostAddress}}/invoices
Accept: application/json

###

GET {{HostAddress}}/invoices/20
Accept: application/json

###

POST {{HostAddress}}/invoices
Content-Type: application/json
{
  "ClientID": 5,
  "Detail": [
    {
      "ProductID": 1,
      "Quantity": 3,
      "Price": 1000
      },
    {
      "ProductID": 5,
      "Quantity": 10,
      "Price": 5000
    }
  ]
}

###

PUT {{HostAddress}}/invoices
Content-Type: application/json
{
  "Id": 17,
  "ClientID": 2,
  "Detail": [
    {
      "ProductID": 4,
      "Quantity": 2,
      "Price": 12000
    },
    {
      "ProductID": 2,
      "Quantity": 2,
      "Price": 2000
    }
  ]
}
###

DELETE {{HostAddress}}/invoices/17
Content-Type: application/json

###


### InvoicesDetails ------------------------------
GET {{HostAddress}}/invoicesdetails
Accept: application/json

###



### Products ------------------------------
GET {{HostAddress}}/products
Accept: application/json

###

GET {{HostAddress}}/products/21
Accept: application/json

###

POST {{HostAddress}}/products
Content-Type: application/json
{
  "Name": "Pantalon",
  "Price": 10800
}
###

PUT {{HostAddress}}/products
Content-Type: application/json
{
  "Id": 6,
  "Name": "Pantaloneta",
  "Price": 10800
}
###

DELETE {{HostAddress}}/products/10
Content-Type: application/json

###

### Client ------------------------------ 
GET {{HostAddress}}/clients
Content-Type: application/json

###

POST {{HostAddress}}/clients
Content-Type: application/json
{
  "Name": "Persona 12"
}
###

PUT {{HostAddress}}/clients
Content-Type: application/json
{
  "Id": 9,
  "Name": "asdasdsd"
}
###

DELETE {{HostAddress}}/clients/9
Content-Type: application/json

###